site_name: Developer Portal Kwaza ICT
site_url: https://devops-portal.kwaza.co
site_description: Developer portal for Kwaza ICT

theme:
    name: material
    palette:
    - scheme: slate # Palette toggle for dark mode
      primary: purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - scheme: default # Palette toggle for light mode
      primary: brown
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    features:
    - content.code.copy
    - navigation.top
    - navigation.instant

extra:
  analytics:
    provider: google
    property: G-8G44E3EEL7

nav:
    - Home: 'index.md'
    - AWS:
        - Data Store:
            - 'About': 'aws/data-store/index.md'
            - 'Storage Gateway': 'aws/data-store/storage-gateway.md'
        - 'AutoScaling':
            - 'Basics': 'aws/architecting-to-scale/index.md'
            - 'Auto scaling': 'aws/architecting-to-scale/auto-scaling.md'
            - 'Compute Optimizer': 'aws/architecting-to-scale/compute-optimizer.md'
            - 'CloudFront': 'aws/architecting-to-scale/cloudfront.md'
            - 'DynamoDB': 'aws/architecting-to-scale/dynamodb-scaling.md'
            - 'Elastic Map Reduce': 'aws/architecting-to-scale/elastic-map-reduce.md'
            - 'Event driven architecture': 'aws/architecting-to-scale/event-driven-architecture.md'
            - 'Kinesis': 'aws/architecting-to-scale/kinesis.md'
            - 'Monitoring and visualizing': 'aws/architecting-to-scale/monitoring-and-visualizing.md'
            - 'Scaling Containers': 'aws/architecting-to-scale/scaling-containers.md'
            - 'Serverless': 'aws/architecting-to-scale/serverless.md'
            - 'SQS': 'aws/architecting-to-scale/sqs.md'
            - 'Step Functions': 'aws/architecting-to-scale/step-functions.md'
            - 'SNS': 'aws/architecting-to-scale/sns.md'
        - Migration:
            - 'About': 'aws/migrations/index.md'
            - 'Hybrid architectures': 'aws/migrations/hybrid-architectures.md'
            - 'Migration applications': 'aws/migrations/migration-applications.md'
            - 'Migrating data': 'aws/migrations/migrating-data.md'
            - 'Network migration': 'aws/migrations/network-migration.md'
            - 'TOGAF': 'aws/migrations/togaf.md'
            - 'Migration tips': 'aws/migrations/migration-tips.md'
        - 'Network':
            - 'About': 'aws/networking/index.md'
            - 'Network to VPC': 'aws/networking/network-to-vpc.md'
            - 'VPC to VPC': 'aws/networking/vpc-to-vpc.md'
            - 'internet gateway': 'aws/networking/internet-gateway.md'
            - 'Enhanced Networking': 'aws/networking/enhanced-networking.md'
            - 'Route Tables': 'aws/networking/routing.md'
            - 'Private Link': 'aws/networking/private-link.md'
            - 'Route 53': 'aws/networking/route53.md'
            - 'Global Accelerator': 'aws/networking/global-accelerator.md'
            - 'Hybrid and cross account network': 'aws/networking/hybrid-and-cross-account-networking.md'
            - 'CloudFront': 'aws/networking/cloudfront.md'
            - 'Elastic Load Balancer': 'aws/networking/elastic-load-balancer.md'
        - 'Cost Management':
            - 'Concept': 'aws/cost-management/index.md'
        - 'Security':
            - 'About': 'aws/security/about.md'
            - 'ControlAccess': 'aws/security/control-access.md'
            - 'Direct Services': 'aws/security/direct-services.md'
            - 'Understand User Access': 'aws/security/understand-user-access.md'
            - 'Multiple Accounts': 'aws/security/multiple-accounts.md'
        - 'Deployment and Operations':
            - 'About': 'aws/deployment-and-operations/index.md'
            - 'ApiGateway': 'aws/deployment-and-operations/api-gateway.md'
            - 'Elastic Beanstalk': 'aws/deployment-and-operations/beanstalk.md'
            - 'CloudFormation': 'aws/deployment-and-operations/cloudformation.md'
            - 'Beanstalk': 'aws/deployment-and-operations/beanstalk.md'
            - 'CI/CD': 'aws/deployment-and-operations/ci-cd.md'
            - 'Deploy Infra Across Accounts': 'aws/deployment-and-operations/deploy-infra-across-accounts.md'
            - 'Enterprise Apps': 'aws/deployment-and-operations/enterprise-apps.md'
            - 'IoT': 'aws/deployment-and-operations/iot-landscape.md'
            - 'Management Tools': 'aws/deployment-and-operations/management-tools.md'
            - 'System Manager': 'aws/deployment-and-operations/system-manager.md'
        - 'Business Continuity':
          - 'About': 'aws/business-continuity/index.md'
          - 'Compute HA': 'aws/business-continuity/compute_ha.md'
          - 'Database HA': 'aws/business-continuity/database_ha.md'
          - 'Disaster Recovery': 'aws/business-continuity/dr.md'
          - 'Storage HA': 'aws/business-continuity/storage_ha.md'
          - 'Network HA': 'aws/business-continuity/network_ha.md'
    - AI:
        - 'Basics':
            - 'Very basic': 'ai/basics/index.md'
            - 'RAG':      'ai/basics/rag.md'
            - 'GenAI': 'ai/gen-ai/index.md'
            - 'Prompt Engineering': 'ai/basics/prompt-engineering.md'
        - 'Machine Learning':
            - 'Basics': 'ai/ml/index.md'
            - 'Training Data': 'ai/ml/training-data.md'
        - 'AWS':
            - 'Sagemaker':
                - 'Basics': 'ai/aws/sagemaker/index.md'
                - 'Canvas': 'ai/aws/sagemaker/canvas.md'
                - 'Clarify': 'ai/aws/sagemaker/clarify.md'
                - 'Data Wrangler': 'ai/aws/sagemaker/data-wrangler.md'
                - 'Ground Truth': 'ai/aws/sagemaker/ground-truth.md'
                - 'JumpStart': 'ai/aws/sagemaker/jumpstart.md'
                - 'ML Governance': 'ai/aws/sagemaker/ml-governance.md'
                - 'Model Monitor': 'ai/aws/sagemaker/model-monitor.md'
                - 'Pipeline': 'ai/aws/sagemaker/pipeline.md'
            - 'BedRock': 'ai/aws/bedrock/index.md'
    - GitHub:
        - 'API':
          - 'Commits': 'github/api/commits.md'
          - 'Releases': 'github/api/releases.md'
          - 'Repository': 'github/api/repository.md'
          - 'Teams': 'github/api/teams.md'
          - 'Runner group': 'github/api/runner-group.md'
        - 'Runners':    'github/runners/bash.md'
        - 'GitHub App': 'github/github-app/get-temp-token.md'
    - GitLab:
        - 'Upgrade':
            - 'Minor version':          'gitlab/upgrade-minor-version.md'
            - 'Upgrade 13 to 14':       'gitlab/13-to-14.md'
            - 'Upgrade 14 to 15':       'gitlab/14-to-15.md'
            - 'Upgrade 15 to 16':       'gitlab/15-to-16.md'
            - 'DB migration':           'gitlab/db-migration.md'
    - Hacking:
        - 'DNS': 'hacking/dns.md'
        - 'Cybersecurity Search Engines': 'hacking/cyber-sec-search-engine.md'
    - Ubuntu:
        - 'APT':
            - 'Commands': 'ubuntu.md'
    - Kubernetes:
        - 'Pods': 'k8s/pods.md'
        - 'Force Pod termination': 'k8s/delete-stuck-pod.md'
    - RedHat:
        - 'subscription': 'redhat/subscription.md'
    - Zsh:
        - 'alias': 'zsh/alias.md'

# -------------------------------------------------------------------
# Extensions: https://squidfunk.github.io/mkdocs-material/setup/extensions/
# -------------------------------------------------------------------
markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  # Allow fences in fences and custom fences like mermaid diagrams
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true

# -------------------------------------------------------------------
# Plugins: https://www.mkdocs.org/dev-guide/plugins/
# -------------------------------------------------------------------
plugins:
  - search
  - mermaid2
